### ISSUE TITLE
Share all the models?

### ISSUE THREAD

**Issue by tommy-qichang** [CardiacAtlasProject/PCATool#1]
Hi there,

Thank you for your great tool.
I just wondering if that possible to share the original model(mask of LA) with us? 
Another quesion is what modality did you used for these 300 cases? CT or MRI? Thanks in advance.

Qi

**Comment by avansp** [comment]
Hi Qi – We don’t have mask of left atrium. Only left ventricle. And these are from MRI images.

 

-- Avan

**Comment by tommy-qichang** [comment]
Yes, I mean if that possible share the 300 cases(Like the mesh or the 3D mask) which is the source to calculate the PCA modes. 
Also it seems the MRI images are more dense along the z-index. Do you use 2D cine MR image or 3D?

Thanks a lot.

**Comment by avansp** [comment]
Hi Qi - sorry for a very long delay to answer.

The models are shared from the Cardiac Atlas Project (http://www.cardiacatlas.org). Since the original MR images are shared through review process, we cannot simply share the 300 cases here. You can apply to get access to these cases, which is the DETERMINE study, from the CAP website.

And these are 2D cine MR images.
